MAX_FUTURE_BLOCK_TIME = 30

FIVE = (10 // 2)

MAX_BLOCK_SIZE = 1_000_000 / FIVE

VALIDATOR_STAKE = 32

VALIDATOR_STAKE_SLASH1 = VALIDATOR_STAKE // 2           # 16 FLA
VALIDATOR_STAKE_SLASH2 = VALIDATOR_STAKE_SLASH1 // 2    # 8 FLA
VALIDATOR_STAKE_SLASH3 = VALIDATOR_STAKE_SLASH2 - 8     # 0 FLA
VALIDATOR_SLASH_STAGES = {
    0x01: VALIDATOR_STAKE_SLASH1,
    0x02: VALIDATOR_STAKE_SLASH2,
    0x03: VALIDATOR_STAKE_SLASH3,
}
